
python 0_main_analyze_discharge.py 17 /scratch-shared/edwin/05min_runs_january_2016_merged/pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave/daily/ discharge_dailyTot_output &
python 0_main_analyze_discharge.py 18 /scratch-shared/edwin/05min_runs_january_2016_merged/pcrglobwb_only_from_1958_4LCs_edwin_parameter_set_kinematic_wave/daily/ discharge_dailyTot_output &
wait
